##################################################
#  _____                                         #
#/\  _ `\   A Cool Guy (ruwey.com)               #
#\ \ \L\ \  __  __  __  __  __    __  __  ___    #
# \ \ ,  / /\ \/\ \/\ \/\ \/\ \ /'__\/\ \/\  \   #
#  \ \ \ \ \ \ \_\ \ \ \_/ \_/ /\  __\ \ \_\  \  #
#   \ \_\ \_\ \____/\ \___x___/\ \____\/\`____ \ #
#    \/_/\/ /\/___/  \/__//__/  \/____/\`/___/> \#
#        ____________________________________\  /#
#       /\_____________________________________/ #
#       \/____________________________________/  #
#                                                #
##################################################

# Config
config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: true
  minversion: 0.29.5
  import_variables:
    - colors/{{@@ colorscheme @@}}.yaml

# Varaibles
variables:
  colorscheme: "Nord"

# Transformations 
trans_read:
  unencrypt: "gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}"
trans_write:
  encrypt: "gpg2 --default-recipient-self --output {1} --encrypt {0}"

# Actions 
actions:

# Dotfiles 
# The first letter indicates the type:
# b     binding
# d     directory
# f     file
dotfiles:
  b_bspwm:
    src: .config/sxhkd/bspwm
    dst: ~/.config/sxhkd/bspwm
  d_awesomewm:
    src: .config/awesome
    dst: ~/.config/awesome
    link: link_children
  d_bspwm:
    src: .config/bspwm
    dst: ~/.config/bspwm
  d_i3:
    src: .config/i3
    dst: ~/.config/i3
    link: link_children
  d_nvim:
    src: .config/nvim
    dst: ~/.config/nvim
  d_pictures:
    src: Pictures
    dst: ~/Pictures
    link: link
  d_polybar:
    src: .config/polybar
    dst: ~/.config/polybar
    link: link_children
  d_scripts:
    src: .scripts
    dst: ~/.scripts
    link: link
  # Spotify Daemon
  f_spotifyd:
    src: .config/spotifyd/spotifyd.conf
    dst: ~/.config/spotifyd/spotifyd.conf
    trans_read: unencrypt
    trans_write: encrypt
  # Generic keybindings
  f_sxhkd:
    src: .config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_zprofile:
    src: .zprofile
    dst: ~/.zprofile
    link: link
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc

# Profiles 
profiles:
  # Desktop
  terminator:
    dotfiles:
    - b_bspwm
      #- d_awesomewm
    - d_bspwm
    - d_i3
    - d_nvim
    - d_pictures
    - d_scripts
    - f_spotifyd
    - f_sxhkd
    - f_zprofile
    - f_zshrc

    variables:
      colorscheme: "Mntns"

  # Laptop
  BigBrother:
    dotfiles:
    - b_bspwm
    - d_bspwm
    - d_nvim
    - d_pictures
    - d_polybar
    - d_scripts
    - f_sxhkd
    - f_spotifyd
    - f_zprofile
    - f_zshrc
