
# Config {{{
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: true
  minversion: 0.29.5
# }}}

# Actions {{{
actions:

#}}}

# Dotfiles {{{
# The first letter indicates the type:
# b     binding
# d     directory
# f     file
dotfiles:
  b_bspwm:
    src: .config/sxhkd/bspwm
    dst: ~/.config/sxhkd/bspwm
    link: link
  d_awesomewm:
    src: .config/awesome
    dst: ~/.config/awesome
    link: link_children
  d_bspwm:
    src: .config/bspwm
    dst: ~/.config/bspwm
    link: link_children
  d_emacs:
    src: .emacs
    dst: ~/
    link: link_children
  d_i3:
    src: .config/i3
    dst: ~/.config/i3
    link: link_children
  d_lutris:
    src: .config/lutris
    dst: ~/.config/lutris
    link: link_children
  d_nvim:
    src: .config/nvim
    dst: ~/.config/nvim
    link: link_children
  d_pictures:
    src: Pictures
    dst: ~/Pictures
    link: link
  d_polybar:
    src: .config/polybar
    dst: ~/.config/polybar
    link: link_children
  d_scripts:
    src: .scripts
    dst: ~/.scripts
    link: link
  # Spotify Daemon
  d_spotifyd:
    src: .config/spotifyd
    dst: ~/.config/spotifyd
    link: link_children
  f_compton.conf:
    src: .config/compton.conf
    dst: ~/.config/compton.conf
    link: link
  # Generic keybindings
  f_sxhkd:
    src: .config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
    link: link
  f_zprofile:
    src: .zprofile
    dst: ~/.zprofile
    link: link
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
    link: link

#}}}

# Profiles {{{
profiles:
  # Desktop
  terminator:
    dotfiles:
    - b_bspwm
      #- d_awesomewm
    - d_bspwm
      #- d_emacs
    - d_i3
    - d_lutris
    - d_nvim
    - d_pictures
    - d_scripts
    - d_spotifyd
    - f_compton.conf
    - f_zprofile
    - f_zshrc
  # Laptop
  BigBrother:
    dotfiles:
    - b_bspwm
    - d_bspwm
    - d_nvim
    - d_pictures
    - d_polybar
    - d_scripts
    - d_spotifyd
    - f_sxhkd
    - f_zprofile
    - f_zshrc
#}}}
# vim:tabstop=2:shiftwidth=2:foldmethod=marker
