config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: true
  minversion: 0.29.5
dotfiles:
  f_zprofile:
    src: .zprofile
    dst: ~/.zprofile
    link: link
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
    link: link
profiles:
  terminator:
    dotfiles:
    - f_zprofile
    - f_zshrc
