config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: true
  minversion: 0.29.5
dotfiles:
  d_nvim:
    src: .config/nvim
    dst: ~/.config/nvim
    link: link_children
  d_pictures:
    src: Pictures
    dst: ~/Pictures
    link: link
  f_zprofile:
    src: .zprofile
    dst: ~/.zprofile
    link: link
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
    link: link
profiles:
  terminator:
    dotfiles:
    - d_nvim
    - d_pictures
    - f_zprofile
    - f_zshrc
