
# Config {{{
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: true
  minversion: 0.29.5
# }}}

# Actions {{{
actions:

#}}}

# Dotfiles {{{
dotfiles:
  d_i3:
    src: .config/i3
    dst: ~/.config/i3
    link: link_children
  d_nvim:
    src: .config/nvim
    dst: ~/.config/nvim
    link: link_children
  d_pictures:
    src: Pictures
    dst: ~/Pictures
    link: link
  d_scripts:
    src: .scripts
    dst: ~/.scripts
    link: link_children
  d_spotifyd:
    src: .config/spotifyd
    dst: ~/.config/spotifyd
    link: link_children
  f_compton.conf:
    src: .config/compton.conf
    dst: ~/.config/compton.conf
    link: link
  f_zprofile:
    src: .zprofile
    dst: ~/.zprofile
    link: link
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
    link: link

#}}}

# Profiles {{{
profiles:
  terminator:
    dotfiles:
    - d_i3
    - d_nvim
    - d_pictures
    - d_scripts
    - d_spotifyd
    - f_compton.conf
    - f_zprofile
    - f_zshrc
  BigBrother:
    dotfiles:
    - d_pictures
    - d_scripts
    - d_spotifyd
    - f_zprofile
    - f_zshrc
#}}}
# vim:tabstop=2:shiftwidth=2:foldmethod=marker
