#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

args=()
if [ "$1" = "-r" ]; then
	args+="-r"
fi

if [ $(polybar -M | wc -l) -eq 1 ]; then
	polybar $args single &
else
	polybar $args main &
	polybar $args right &
fi

echo "Polybar launched..."
