#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if [ "$1" = "-r" ]
then
	polybar -r main &
	polybar -r right &
else
	polybar main &
	polybar right &
fi

# Launch Polybar, using default config location ~/.config/polybar/config

echo "Polybar launched..."
