#!/bin/sh

$HOME/.config/bspwm/autostart.sh &
sxhkd $HOME/.config/sxhkd/bspwm &

mons="$(xrandr | grep " connected" | awk '{ print $1 }' | wc -l)"
echo $mons
if [ $mons -gt 1 ]
then
	bspc monitor eDP-1-1 -d 1 2 3 4 5
	bspc monitor HDMI-0 -d 6 7 8 9 10
	xrandr --output HDMI-0 --right-of eDP-1-1
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         0
bspc config window_gap          12

bspc config pointer_modifier     mod1
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Wpg state=floating
bspc rule -a Steam desktop=5
# Tridactyl nvim entry
bspc rule -a Termite:browserEditor state=floating
# Firefox picture in picture
bspc rule -a firefox:Toolkit sticky=on
# Make emacs tiled
bspc rule -a Emacs state=tiled

