#!/bin/sh

$HOME/.config/autostart.sh &

sxhkd $HOME/.config/bspwm/bindings &

# Polybar (bar)
#{%@@ if colorscheme == "Nord" @@%}#
$HOME/.config/polybar/launch.sh &
#{%@@ endif @@%}#

#{%@@ if profile == "terminator" @@%}#
mons=($(xrandr | grep " connected" | awk '{ print $1 }'))
if [ ${#mons[*]} -gt 1 ]
then
	bspc monitor ${mons[0]} -d 1 2 3 4 5
	bspc monitor ${mons[1]} -d 6 7 8 9 10
	xrandr --output ${mons[0]} --left-of ${mons[1]}
	bspc desktop -f 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi
#{%@@ else @@%}#
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#{%@@ endif @@%}#

#{%@@ if colorscheme == "Mntns" @@%}#
bspc config border_width	0
bspc config window_gap		20
#{%@@ elif colorscheme == "Nord" @@%}#
bspc config border_width	2
bspc config window_gap		18
#{%@@ endif @@%}#


bspc config pointer_modifier	mod4
bspc config split_ratio		0.5

bspc rule -a Wpg state=floating
bspc rule -a Steam desktop=6
bspc rule -a Surf state=tiled
# Tridactyl nvim entry
bspc rule -a Termite:browserEditor state=floating
# Firefox picture in picture
bspc rule -a firefox:Toolkit sticky=on state=floating
# Make emacs tiled
bspc rule -a Emacs state=tiled
# Make yubico authentication
bspc rule -a Yubico\ Authenticator rectange=952x800 \
	state=floating center=on sticky=on
# Gnome Calculator
bspc rule -a Gnome-calculator:gnome-calculator state=floating
# Rules for font preview
bspc rule -a \*:fontpreview state=floating
bspc rule -a Termite:fontpreiew rectangle=493x635+2634+387
bspc rule -a Sxiv:fontpreview \
	rectangle=493x325+2634+47

# Set up a scratchpad window
bspc rule -a Scratch:\* \
	state=floating \
	hidden=on \
	sticky=on

# Set up terminal scratchpad 
bspc rule -a Scratch:term \
	rectangle=800x200+1116+840
