# Qutebrowser Config
# Ruwey (ruwey.com)

# Keybindings {{{
binds:
  normal:
    <Ctrl+Shift+f>: spawn --user qute-pass
    <Ctrl+j>: tab-move -
    <Ctrl+k>: tab-move +
    j: run-with-count 2 scroll down
    k: run-with-count 2 scroll up
    d: null
    dd: tab-close
    po: set-cmd-text -s :open -p
    pO: set-cmd-text :open -p {url:pretty}
    zi: zoom-in
    zo: zoom-out
    zz: zoom
    tt: config-cycle tabs.width 32 15%
    # Toggle Ad Blocking
    ",ta": config-cycle content.blocking.adblock.enabled
    ",tb": config-cycle tabs.show never always
    ",ts": config-cycle statusbar.show never always
    ",ff": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret'
    ",fp": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --password-only'
    ",fu": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --username-only'
    ",vo": spawn -u view_in_mpv
  insert:
    <Ctrl+e>: null
# }}}

# Settings {{{
settings:
  global:
    spellcheck.languages:
      - en-US
    url.searchengines:
      DEFAULT: "https://duckduckgo.com/?q={}" # Default Search Engine: DuckDuckGO
      gh: "https://github.com/search?q={}" # Github
      yt: "https://www.youtube.com/results?search_query={}" # Youtube
      r/: "https://reddit.com/r/{}"
      r/s: "https://www.reddit.com/search/?q={}"
      itad: "https://isthereanydeal.com/search/?q={}" # Is There Any Deal
      aur: "https://aur.archlinux.org/packages/?O=0&K={}"
      protondb: "https://www.protondb.com/search?q={}"
      wirecutter: "https://www.nytimes.com/wirecutter/search/?s={}"
    content.notifications: false
    content.autoplay: false
    auto_save.session: true
    
    # Tab Bar
    tabs.position: "left"
    tabs.padding: {"bottom": 8, "left": 0, "right": 3, "top": 8}
    tabs.favicons.scale: 1.5

    #"*://www.reddit.com/*":
    # Fix comments not loading on reddit. (Ads are unblock-able anyway)
    #content.blocking.adblock.enabled: false
# }}}

# sup
