# Qutebrowser Config
# Ruwey (ruwey.com)

# Keybindings {{{
binds:
  normal:
    <Ctrl+Shift+f>: spawn --user qute-pass
    <Ctrl+j>: tab-move -
    <Ctrl+k>: tab-move +
    J: tab-prev
    K: tab-next
    d: null
    dd: tab-close
    po: set-cmd-text -s :open -p
    zi: zoom-in
    zo: zoom-out
    zvo: spawn -u view_in_mpv
    zz: zoom
    # Toggle Ad Blocking
    ",ta": config-cycle content.blocking.adblock.enabled
    ",tb": config-cycle tabs.show never always
    ",ts": config-cycle statusbar.hide
    ",ff": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret'
    ",fp": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --password-only'
    ",fu": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --username-only'
# }}}

# Settings {{{
settings:
  global:
    spellcheck.languages:
      - en-US
    url.searchengines:
      DEFAULT: "https://duckduckgo.com/?q={}" # Default Search Engine: DuckDuckGO
      gh: "https://github.com/search?q={}" # Github
      yt: "https://www.youtube.com/results?search_query={}" # Youtube
      r/: "https://reddit.com/r/{}"
      r/s: "https://www.reddit.com/search/?q={}"
      itad: "https://isthereanydeal.com/search/?q={}" # Is There Any Deal
      aur: "https://aur.archlinux.org/packages/?O=0&K={}"
      protondb: "https://www.protondb.com/search?q={}"
      wirecutter: "https://www.nytimes.com/wirecutter/search/?s={}"
    content.notifications: false
    auto_save.session: true
  "*://www.reddit.com/*":
    # Fix comments not loading on reddit. (Ads are unblock-able anyway)
    content.blocking.adblock.enabled: false
# }}}

# sup
