#!/bin/bash
# change Volume
# chVol CHANGE 

XOB=/tmp/to-xob

# The notification id for dunst
msgId="990099"
# The sink to use
sink="$(pactl info | grep "Default Sink" | cut -d' ' -f3)"

# Actually change volume
if [[ $@ = 'mute' ]]; then
	pactl -- set-sink-mute $sink toggle # What to do if chVol is followed by mute
else
	pactl -- set-sink-volume "$sink" $@ # What to do if a number follows chVol
fi

# Notification
# Get volume of the sink
volume="$(pactl list sinks | grep -A 7 "Name: $sink" | tail -1 | sed 's/[/%]//g' | awk '{print $4}')"
# Wether the sink is muted
mute="$(pactl list sinks | grep -A 6 "Name: $sink" | tail -1 | awk '{print $2}')"

if [ ! -n "$(pgrep -x xob)" ]; then
	(tail -f $XOB | xob) &
fi

if [ $mute = 'yes' ]; then
	echo "$volume!" >> $XOB
else
	echo "$volume" >> $XOB
fi

#if [[ $volume == 0 || $mute == yes ]]; then
#	# If Muted
#	dunstify -a "chVol" -u low -r "$msgId" "Volume Muted"
#else
#	dunstify -a "chVol" -u low -i audio-volume-high -r "$msgId" \
#		"墳 Volume: ${volume}%" "$(getProg 20 "▉" "-" $volume)"
#fi
