#!/bin/bash
# change Volume
# chVol CHANGE 

# The notification id for dunst
msgId="990099"
# The sink to use
sink="$(pacmd stat | grep "Default sink" | awk '{print $4}')"

# Actually change volume
if [[ $@ = 'mute' ]]; then
	pactl -- set-sink-mute $sink toggle # What to do if chVol is followed by mute
else
	pactl -- set-sink-volume "$sink" $@ # What to do if a number follows chVol
fi

# Notification
# Get volume of the sink
volume="$(pacmd list-sinks | grep -C 6 "$sink" | tail -1 | sed 's/[/%]//g' | awk '{print $4}')"
# Wether the sink is muted
mute="$(pacmd list-sinks | grep -C 10 "$sink" | tail -1 | awk '{print $2}')"

if [[ $volume == 0 || $mute == yes ]]; then
	# If Muted
	dunstify -a "chVol" -u low -r "$msgId" "Volume Muted"
else
	dunstify -a "chVol" -u low -i audio-volume-high -r "$msgId" \
		"墳 Volume: ${volume}%" "$(getProg 20 "▉" "-" $volume)"
fi
