#!/bin/bash

dmenu="rofi -dmenu"

function lutrisLaunch {
	gamesList=$(lutris -lo)
	
	gameChoice=$(echo "$gamesList" | awk -F \| '{print $2$4 }'| $dmenu -i | awk -F "  " '{print $1}')
	
	game=$(echo "$gamesList" | grep "$gameChoice" | awk -F \| '{print $3}' | sed "s/ //g")
	
	lutris lutris:rungame/$game
}

launchers=(Lutris/Steam
	   RetroArch)

launcher="$(printf '%s\n' "${launchers[@]}" | $dmenu)"

case $launcher in
	"Lutris/Steam")
		lutrisLaunch;;
	"RetroArch")
		;;
esac
