#!/bin/bash

gamesList=$(lutris -lo)

gameChoice=$(echo "$gamesList" | awk -F \| '{print $2$4 }'| rofi -dmenu -i | awk -F "  " '{print $1}')

game=$(echo "$gamesList" | grep "$gameChoice" | awk -F \| '{print $3}' | sed "s/ //g")

lutris lutris:rungame/$game
