#!/bin/sh
# Power Menu Script

# Dmenu Comand
dcmd="${DMENU_CMD:-dmenu}"

# Get what user wants to do
action=$(echo -e "Power Down\nReboot\nSuspend\nHibernate\nLock\nBlank Screen" | $dcmd -i)

case $action in
	"Power Down")
		#loginctl poweroff
		dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
		;;
	"Reboot")
		loginctl reboot
		dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
		;;
	"Suspend")
		blurlock -s
		;;
	"Hibernate")
		blurlock -h
		;;
	"Lock")
		blurlock
		;;
	"Blank Screen")
		sleep 3
		xset dpms force off
		;;
esac
